### ISSUE TITLE
model directory confusion

### ISSUE THREAD

**Issue by tzktok** [camenduru/memo-tost#1]
Could you share the models directory folder structure ... confusion between directory and model paths @camenduru

**Comment by camenduru** [comment]
/content/memo/checkpoints/audio_proj -o config.json
/content/memo/checkpoints/audio_proj -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/diffusion_net -o config.json
/content/memo/checkpoints/diffusion_net -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/image_proj -o config.json
/content/memo/checkpoints/image_proj -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/misc/audio_emotion_classifier -o config.json
/content/memo/checkpoints/misc/audio_emotion_classifier -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/misc/face_analysis/models -o 1k3d68.onnx
/content/memo/checkpoints/misc/face_analysis/models -o 2d106det.onnx
/content/memo/checkpoints/misc/face_analysis/models -o face_landmarker_v2_with_blendshapes.task
/content/memo/checkpoints/misc/face_analysis/models -o genderage.onnx
/content/memo/checkpoints/misc/face_analysis/models -o glintr100.onnx
/content/memo/checkpoints/misc/face_analysis/models -o scrfd_10g_bnkps.onnx
/content/memo/checkpoints/misc/vocal_separator -o Kim_Vocal_2.onnx
/content/memo/checkpoints/misc/vocal_separator -o download_checks.json
/content/memo/checkpoints/misc/vocal_separator -o mdx_model_data.json
/content/memo/checkpoints/misc/vocal_separator -o vr_model_data.json
/content/memo/checkpoints/reference_net -o config.json
/content/memo/checkpoints/reference_net -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/vae -o diffusion_pytorch_model.safetensors
/content/memo/checkpoints/vae -o config.json
/content/memo/checkpoints/wav2vec2 -o model.safetensors
/content/memo/checkpoints/wav2vec2 -o config.json
/content/memo/checkpoints/wav2vec2 -o preprocessor_config.json
/content/memo/checkpoints/emotion2vec_plus_large -o model.pt
/content/memo/checkpoints/emotion2vec_plus_large -o config.yaml
/content/memo/checkpoints/emotion2vec_plus_large -o configuration.json
/content/memo/checkpoints/emotion2vec_plus_large -o tokens.txt

**Comment by tzktok** [comment]
thank you @camenduru  !!!
